-- MySQL Script generated by MySQL Workbench
-- Tue Apr 23 22:49:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema attendenssystem
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `attendenssystem` ;

-- -----------------------------------------------------
-- Schema attendenssystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `attendenssystem` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `attendenssystem` ;

-- -----------------------------------------------------
-- Table `attendenssystem`.`faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendenssystem`.`faculty` (
  `FacultyID` INT NOT NULL AUTO_INCREMENT,
  `FacultyName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`FacultyID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `attendenssystem`.`speciality`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendenssystem`.`speciality` (
  `SpecialityID` INT NOT NULL AUTO_INCREMENT,
  `SpecialityName` VARCHAR(100) NOT NULL,
  `FacultyID` INT NOT NULL,
  PRIMARY KEY (`SpecialityID`),
  INDEX `facultyID_idx` (`FacultyID` ASC) VISIBLE,
  CONSTRAINT `facultyID`
    FOREIGN KEY (`FacultyID`)
    REFERENCES `attendenssystem`.`faculty` (`FacultyID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `attendenssystem`.`lector`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendenssystem`.`lector` (
  `LectorID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(100) NOT NULL,
  `LastName` VARCHAR(100) NOT NULL,
  `Tel` VARCHAR(20) NOT NULL,
  `SpecialityID` INT NOT NULL,
  `Photo` TEXT NOT NULL,
  PRIMARY KEY (`LectorID`),
  INDEX `SpecialityID_idx` (`SpecialityID` ASC) VISIBLE,
  CONSTRAINT `SpecialityID`
    FOREIGN KEY (`SpecialityID`)
    REFERENCES `attendenssystem`.`speciality` (`SpecialityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `attendenssystem`.`class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendenssystem`.`class` (
  `ClassID` INT NOT NULL AUTO_INCREMENT,
  `ClassName` VARCHAR(100) NOT NULL,
  `SpecialityID` INT NOT NULL,
  PRIMARY KEY (`ClassID`),
  INDEX `SpecialityID_idx` (`SpecialityID` ASC) VISIBLE,
  CONSTRAINT `SpecialityID`
    FOREIGN KEY (`SpecialityID`)
    REFERENCES `attendenssystem`.`speciality` (`SpecialityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `attendenssystem`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendenssystem`.`courses` (
  `CourseID` INT NOT NULL AUTO_INCREMENT,
  `CourseName` VARCHAR(100) NOT NULL,
  `Credit` INT NOT NULL,
  `Semestre` INT NOT NULL,
  `SpecialityID` INT NOT NULL,
  PRIMARY KEY (`CourseID`),
  INDEX `SpecialityID_idx` (`SpecialityID` ASC) VISIBLE,
  CONSTRAINT `SpecialityID`
    FOREIGN KEY (`SpecialityID`)
    REFERENCES `attendenssystem`.`speciality` (`SpecialityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `attendenssystem`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendenssystem`.`schedule` (
  `ScheduleID` INT NOT NULL AUTO_INCREMENT,
  `CourseID` INT NOT NULL,
  `ClassID` INT NOT NULL,
  `LectorID` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  PRIMARY KEY (`ScheduleID`),
  INDEX `LectorID_idx` (`LectorID` ASC) VISIBLE,
  INDEX `ClassID_idx` (`ClassID` ASC) VISIBLE,
  INDEX `CourseID_idx` (`CourseID` ASC) VISIBLE,
  CONSTRAINT `LectorID`
    FOREIGN KEY (`LectorID`)
    REFERENCES `attendenssystem`.`lector` (`LectorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ClassID`
    FOREIGN KEY (`ClassID`)
    REFERENCES `attendenssystem`.`class` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CourseID`
    FOREIGN KEY (`CourseID`)
    REFERENCES `attendenssystem`.`courses` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `attendenssystem`.`attandance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendenssystem`.`attandance` (
  `AttandanceID` INT NOT NULL AUTO_INCREMENT,
  `PersonID` INT NOT NULL,
  `ScheduleID` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Who` TINYINT(1) NOT NULL,
  `Late` INT NOT NULL,
  PRIMARY KEY (`AttandanceID`),
  INDEX `ScheduleID_idx` (`ScheduleID` ASC) VISIBLE,
  CONSTRAINT `ScheduleID`
    FOREIGN KEY (`ScheduleID`)
    REFERENCES `attendenssystem`.`schedule` (`ScheduleID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `attendenssystem`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `attendenssystem`.`student` (
  `StudentID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(100) NOT NULL,
  `LastName` VARCHAR(100) NOT NULL,
  `ClassID` INT NOT NULL,
  `Photo` TEXT NOT NULL,
  PRIMARY KEY (`StudentID`),
  INDEX `classID_idx` (`ClassID` ASC) VISIBLE,
  CONSTRAINT `classID`
    FOREIGN KEY (`ClassID`)
    REFERENCES `attendenssystem`.`class` (`ClassID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
